# Generated by Django 3.1.6 on 2021-02-23 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deelnemers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailadres', models.CharField(default='', max_length=45)),
                ('activiteit', models.CharField(default='', max_length=45)),
                ('optional', models.CharField(default='', max_length=45)),
                ('doelstellingen', models.CharField(default='', max_length=45)),
                ('pointscore', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Scorekaart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(default='', max_length=45)),
                ('achternaam', models.CharField(default='', max_length=45)),
                ('optional', models.CharField(default='', max_length=45)),
                ('jaar', models.IntegerField(default=1)),
                ('maand', models.IntegerField(default=1)),
                ('week', models.IntegerField(default=1)),
                ('dag', models.IntegerField(default=1)),
                ('duur', models.IntegerField(default=1)),
                ('start_tijd', models.DateTimeField(default=-2020)),
                ('eind_tijd', models.DateTimeField(default=-2020)),
                ('emailadres', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.deelnemers')),
            ],
        ),
        migrations.CreateModel(
            name='PersoonsGegevens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(default='', max_length=45)),
                ('achternaam', models.CharField(default='', max_length=45)),
                ('optional', models.CharField(default='', max_length=45)),
                ('gewicht', models.IntegerField(default=1)),
                ('leeftijd', models.IntegerField(default=1)),
                ('lengte', models.IntegerField(default=1)),
                ('emailadres', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.deelnemers')),
            ],
        ),
        migrations.CreateModel(
            name='Activiteiten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activiteit', models.CharField(default='', max_length=45)),
                ('eenheid', models.CharField(default='', max_length=45)),
                ('optional', models.CharField(default='', max_length=45)),
                ('multiplier', models.FloatField(default=1)),
                ('punten', models.IntegerField(default=1)),
                ('emailadres', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.deelnemers')),
            ],
        ),
    ]
