# Generated by Django 3.1.6 on 2021-02-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deelnemers',
            name='emailadres',
        ),
        migrations.AddField(
            model_name='deelnemers',
            name='emailadres_a',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.activiteiten'),
        ),
        migrations.AddField(
            model_name='deelnemers',
            name='emailadres_p',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.persoonsgegevens'),
        ),
        migrations.AddField(
            model_name='deelnemers',
            name='emailadres_s',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.scorekaart'),
        ),
        migrations.AlterField(
            model_name='activiteiten',
            name='emailadres',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='persoonsgegevens',
            name='emailadres',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='scorekaart',
            name='emailadres',
            field=models.CharField(default='', max_length=45),
        ),
    ]
