# Generated by Django 3.1.6 on 2021-02-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210223_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorekaart',
            name='eind_tijd',
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name='scorekaart',
            name='start_tijd',
            field=models.DateTimeField(default=0),
        ),
    ]
