# Generated by Django 3.1.6 on 2021-02-24 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210224_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deelnemers',
            name='pointscore',
        ),
        migrations.RemoveField(
            model_name='scorekaart',
            name='deelnemers',
        ),
        migrations.AddField(
            model_name='persoonsgegevens',
            name='deelnemers',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.deelnemers'),
        ),
    ]
