# Generated by Django 3.1.6 on 2021-02-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210224_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deelnemers',
            new_name='Doelstellingen',
        ),
    ]
