# Generated by Django 3.1.6 on 2021-02-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210224_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persoonsgegevens',
            old_name='deelnemers',
            new_name='doelstellingen',
        ),
    ]
