# Generated by Django 3.1.6 on 2021-02-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210224_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persoonsgegevens',
            name='doelstellingen',
        ),
        migrations.AddField(
            model_name='doelstellingen',
            name='persoonsgegevens',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.persoonsgegevens'),
        ),
    ]
