# Generated by Django 3.1.6 on 2021-02-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210224_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorekaart',
            name='achternaam',
        ),
        migrations.RemoveField(
            model_name='scorekaart',
            name='voornaam',
        ),
    ]
