# Generated by Django 3.1.6 on 2021-02-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_doelstellingen_activiteiten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doelstellingen',
            name='activiteit',
        ),
    ]
