# Generated by Django 3.1.6 on 2021-02-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_doelstellingen_activiteit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doelstellingen',
            name='doelstellingen',
            field=models.IntegerField(default='', max_length=45),
        ),
    ]
