# Generated by Django 3.1.6 on 2021-02-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210224_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activiteiten',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='doelstellingen',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='persoonsgegevens',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='scorekaart',
            name='optional',
        ),
    ]
