# Generated by Django 3.1.6 on 2021-02-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210224_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doelstellingen',
            name='doelstellingen',
            field=models.IntegerField(default=0),
        ),
    ]
