# Generated by Django 3.1.6 on 2021-02-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210224_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persoonsgegevens',
            options={'verbose_name': 'Persoonsgegevens', 'verbose_name_plural': 'Persoonsgegevens'},
        ),
    ]
