# Generated by Django 3.1.6 on 2021-02-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20210226_0934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activiteiten',
            options={'verbose_name': 'Activiteiten', 'verbose_name_plural': 'Activiteiten'},
        ),
        migrations.AlterModelOptions(
            name='doelstellingen',
            options={'verbose_name': 'Doelstellingen', 'verbose_name_plural': 'Doelstellingen'},
        ),
        migrations.AlterModelOptions(
            name='scorekaart',
            options={'verbose_name': 'Scorekaart', 'verbose_name_plural': 'Scorekaart'},
        ),
    ]
