# Generated by Django 3.1.6 on 2021-02-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20210226_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doelstellingen',
            old_name='doelstellingen',
            new_name='doelstelling',
        ),
    ]
