# Generated by Django 3.1.6 on 2021-02-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210227_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorekaart',
            name='punten',
            field=models.IntegerField(default=1),
        ),
    ]
