# Generated by Django 3.1.6 on 2021-02-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteiten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activiteit', models.CharField(default='', max_length=45)),
                ('eenheid', models.CharField(default='', max_length=45)),
                ('multiplier', models.FloatField(default=1)),
                ('punten', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Activiteiten',
                'verbose_name_plural': 'Activiteiten',
            },
        ),
        migrations.CreateModel(
            name='PersoonsGegevens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailadres', models.CharField(default='', max_length=45)),
                ('voornaam', models.CharField(default='', max_length=45)),
                ('achternaam', models.CharField(default='', max_length=45)),
                ('gewicht', models.IntegerField(default=1)),
                ('leeftijd', models.IntegerField(default=1)),
                ('lengte', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Persoonsgegevens',
                'verbose_name_plural': 'Persoonsgegevens',
            },
        ),
        migrations.CreateModel(
            name='Scorekaart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.IntegerField(default=1)),
                ('maand', models.IntegerField(default=1)),
                ('week', models.IntegerField(default=1)),
                ('dag', models.IntegerField(default=1)),
                ('duur', models.IntegerField(default=1)),
                ('start_tijd', models.DateTimeField(default=0)),
                ('eind_tijd', models.DateTimeField(default=0)),
                ('activiteiten', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userentry.activiteiten')),
                ('persoonsgegevens', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userentry.persoonsgegevens')),
            ],
            options={
                'verbose_name': 'Scorekaart',
                'verbose_name_plural': 'Scorekaart',
            },
        ),
        migrations.CreateModel(
            name='Doelstellingen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doelstellingen', models.IntegerField(default=0)),
                ('activiteiten', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userentry.activiteiten')),
                ('persoonsgegevens', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userentry.persoonsgegevens')),
            ],
            options={
                'verbose_name': 'Doelstellingen',
                'verbose_name_plural': 'Doelstellingen',
            },
        ),
    ]
